// 单位性质
export const UNIT_KIND = [
  {dicItemCode: '101', dicItemName: '行政机关'},
  {dicItemCode: '105', dicItemName: '行政执法'},
  {dicItemCode: '104', dicItemName: '参公管理类事业单位'},
  {dicItemCode: '103', dicItemName: '事业单位'},
  {dicItemCode: '106', dicItemName: '群团机关'},
  {dicItemCode: '107', dicItemName: '参公管理类群团机关'},
];

// 单位性质PAD
export const UNIT_KIND_PAD = [
  {dicItemCode: '1', dicItemName: '机关单位'},
  {dicItemCode: '2', dicItemName: '参公单位'},
  {dicItemCode: '3', dicItemName: '事业单位'},
];


// 机构级别
export const LEVEL = [
  {dicItemCode: '101', dicItemName: '正省级'},
  {dicItemCode: '102', dicItemName: '正市级'},
  {dicItemCode: '103', dicItemName: '副市（正厅）级'},
  {dicItemCode: '104', dicItemName: '正局级'},
  {dicItemCode: '105', dicItemName: '副局级'},
  {dicItemCode: '106', dicItemName: '正处级'},
  {dicItemCode: '107', dicItemName: '副处级'},
  {dicItemCode: '108', dicItemName: '正科级'},
  {dicItemCode: '109', dicItemName: '副科级'},
  {dicItemCode: '112', dicItemName: '不定级'},
  {dicItemCode: '113', dicItemName: '未定级'},
  {dicItemCode: '124', dicItemName: '三级'},
  {dicItemCode: '125', dicItemName: '四级'},
  {dicItemCode: '126', dicItemName: '五级'},
  {dicItemCode: '127', dicItemName: '六级'},
  {dicItemCode: '128', dicItemName: '七级'},
  {dicItemCode: '129', dicItemName: '八级'},
  {dicItemCode: '130', dicItemName: '九级'},
  {dicItemCode: '131', dicItemName: '十级'},
];

// 系统类别
export const UNIT_CATEGORY = [
  {dicItemCode: '1', dicItemName: '党委系统'},
  {dicItemCode: '2', dicItemName: '人大系统'},
  {dicItemCode: '3', dicItemName: '政府系统'},
  {dicItemCode: '5', dicItemName: '政协系统'},
  {dicItemCode: '6', dicItemName: '民主党派系统'},
  {dicItemCode: '7', dicItemName: '群众团体系统'},
  {dicItemCode: 'b', dicItemName: '其他系统'},
];

// 经费形式
export const BUDGET_FROM = [
  {dicItemCode: '19', dicItemName: '财政核拨'},
  {dicItemCode: '20', dicItemName: '财政核拨补助'},
  {dicItemCode: '21', dicItemName: '财政核拨补助（定项）'},
  {dicItemCode: '22', dicItemName: '经费自理'},
  {dicItemCode: '23', dicItemName: '经费自理（企业化管理）'},
];

// 事业单位分类
export const SY_UNIT_CLASS = [
  {dicItemCode: '1', dicItemName: '行政类'},
  {dicItemCode: '2', dicItemName: '公益一类'},
  {dicItemCode: '21', dicItemName: '公益二类'},
  {dicItemCode: '22', dicItemName: '公益三类'},
  {dicItemCode: '3', dicItemName: '生产经营类'},
  {dicItemCode: '8', dicItemName: '未分类'},
  {dicItemCode: '9', dicItemName: '暂缓分类'},
];

// 编制类型
export const HC = [
  {dicItemCode: '1', dicItemName: '行政编制'},
  {dicItemCode: '2', dicItemName: '地税专项编制'},
  {dicItemCode: '3', dicItemName: '基层工商行政编制'},
  {dicItemCode: '4', dicItemName: '基层质监行政编制'},
  {dicItemCode: '5', dicItemName: '基层药监行政编制'},
  {dicItemCode: '150', dicItemName: '单列编制'},
  {dicItemCode: '11', dicItemName: '公安专项编制'},
  {dicItemCode: '12', dicItemName: '检察院专项编制'},
  {dicItemCode: '13', dicItemName: '法院专项编制'},
  {dicItemCode: '14', dicItemName: '司法行政专项编制'},
  {dicItemCode: '15', dicItemName: '劳教专项编制'},
  {dicItemCode: '16', dicItemName: '监狱专项编制'},
  {dicItemCode: '17', dicItemName: '森林公安专项编制'},
  {dicItemCode: '18', dicItemName: '政法专项编制'},
  {dicItemCode: '3729', dicItemName: '法定机构员额'},
  {dicItemCode: '20', dicItemName: '机关事业编制'},
  {dicItemCode: '24', dicItemName: '高级雇员员额'},
  {dicItemCode: '25', dicItemName: '专业技术雇员员额'},
  {dicItemCode: '26', dicItemName: '辅助管理雇员员额'},
  {dicItemCode: '27', dicItemName: '工勤雇员员额'},
  {dicItemCode: '28', dicItemName: '行政执法专项编制'},
  {dicItemCode: '75', dicItemName: '行政管理类事业编制'},
  {dicItemCode: '78', dicItemName: '群团机关使用的事业编制'},
  {dicItemCode: '299', dicItemName: '编外用人规模'},
  {dicItemCode: '101', dicItemName: '辅助管理类(老干)雇员'},
  {dicItemCode: '102', dicItemName: '行政事务编制'},
  {dicItemCode: '103', dicItemName: '附属编制'},
  {dicItemCode: '104', dicItemName: '事业编制'},
  {dicItemCode: '111', dicItemName: '单位自聘人员定额'},
  {dicItemCode: '112', dicItemName: '临聘人员定额'},
  {dicItemCode: '113', dicItemName: '法定机构授薪员额'},
  {dicItemCode: '120', dicItemName: '军队转业干部行政编制'},
  {dicItemCode: '200', dicItemName: '机动员额'},
  {dicItemCode: '1000', dicItemName: '公务员编制类'},
  {dicItemCode: '2000', dicItemName: '事业编制类'},
  {dicItemCode: '3000', dicItemName: '工勤雇员编制类'},
  {dicItemCode: '4000', dicItemName: '单列编制类'},
  {dicItemCode: '5000', dicItemName: '其他编制类'},
  {dicItemCode: '557434', dicItemName: '专业类聘任制公务员编制'},
  {dicItemCode: '557732', dicItemName: '辅助管理类聘任制公务员编制'},
];

// 职务属性
export const DUTY_ATTRIBUTE = [
  {dicItemCode: '010110', dicItemName: '单位领导'},
  {dicItemCode: '010120', dicItemName: '内设机构领导'},
  {dicItemCode: '030', dicItemName: '非领导职务'},
];

// 职务层次
export const DUTY_LEVEL = [
  {dicItemCode: '010', dicItemName: '机关单位行政职务层次'},
  {dicItemCode: '010001', dicItemName: '主席、副主席、总理'},
  {dicItemCode: '010002', dicItemName: '副总理、国务委员'},
  {dicItemCode: '010010', dicItemName: '正省级'},
  {dicItemCode: '010011', dicItemName: '副省级'},
  {dicItemCode: '010020', dicItemName: '正市级（深圳）'},
  {dicItemCode: '010030', dicItemName: '副市级（深圳）'},
  {dicItemCode: '010040', dicItemName: '正局级（深圳）'},
  {dicItemCode: '010041', dicItemName: '正厅级'},
  {dicItemCode: '010050', dicItemName: '副局级（深圳）'},
  {dicItemCode: '010051', dicItemName: '副厅级'},
  {dicItemCode: '010060', dicItemName: '正处级'},
  {dicItemCode: '010070', dicItemName: '副处级'},
  {dicItemCode: '010080', dicItemName: '正科级'},
  {dicItemCode: '010090', dicItemName: '副科级'},
  {dicItemCode: '010100', dicItemName: '科员'},
  {dicItemCode: '010110', dicItemName: '办事员'},
  {dicItemCode: '010120', dicItemName: '未定级'},
  {dicItemCode: '011', dicItemName: '行政执法类公务员职务层次'},
  {dicItemCode: '011000', dicItemName: '高级执法员'},
  {dicItemCode: '011010', dicItemName: '一级执法员'},
  {dicItemCode: '011020', dicItemName: '二级执法员'},
  {dicItemCode: '011030', dicItemName: '三级执法员'},
  {dicItemCode: '011040', dicItemName: '四级执法员'},
  {dicItemCode: '011050', dicItemName: '五级执法员'},
  {dicItemCode: '011060', dicItemName: '六级执法员'},
  {dicItemCode: '011070', dicItemName: '七级执法员'},
  {dicItemCode: '011080', dicItemName: '助理执法员'},
  {dicItemCode: '011090', dicItemName: '见习执法员'},
  {dicItemCode: '011100', dicItemName: '未定级'},
  {dicItemCode: '012', dicItemName: '专业技术类公务员职务层次'},
  {dicItemCode: '012010', dicItemName: '专业技术一级'},
  {dicItemCode: '012020', dicItemName: '专业技术二级'},
  {dicItemCode: '012030', dicItemName: '专业技术三级'},
  {dicItemCode: '012040', dicItemName: '专业技术四级'},
  {dicItemCode: '012050', dicItemName: '专业技术五级'},
  {dicItemCode: '012060', dicItemName: '专业技术六级'},
  {dicItemCode: '012070', dicItemName: '专业技术七级'},
  {dicItemCode: '012080', dicItemName: '专业技术八级'},
  {dicItemCode: '012090', dicItemName: '专业技术九级'},
  {dicItemCode: '012100', dicItemName: '专业技术十级'},
  {dicItemCode: '012110', dicItemName: '专业技术十一级'},
  {dicItemCode: '012120', dicItemName: '专业技术十二级'},
  {dicItemCode: '012130', dicItemName: '专业技术十三级'},
  {dicItemCode: '012140', dicItemName: '专业技术十四级'},
  {dicItemCode: '012150', dicItemName: '专业技术十五级'},
  {dicItemCode: '012160', dicItemName: '专业技术十六级'},
  {dicItemCode: '012170', dicItemName: '专业技术十七级'},
  {dicItemCode: '012180', dicItemName: '专业技术十八级'},
  {dicItemCode: '012190', dicItemName: '专业技术十九级'},
  {dicItemCode: '012200', dicItemName: '专业技术二十级'},
  {dicItemCode: '012300', dicItemName: '未定级'},
  {dicItemCode: '020', dicItemName: '事业单位行政职务层次'},
  {dicItemCode: '020010', dicItemName: '一级职员（正部）'},
  {dicItemCode: '020015', dicItemName: '一级职员（正市）'},
  {dicItemCode: '020020', dicItemName: '二级职员（副部）'},
  {dicItemCode: '020025', dicItemName: '二级职员（副市）'},
  {dicItemCode: '020030', dicItemName: '三级职员（正厅）'},
  {dicItemCode: '020035', dicItemName: '三级职员（正局）'},
  {dicItemCode: '020040', dicItemName: '四级职员（副厅）'},
  {dicItemCode: '020045', dicItemName: '四级职员（副局）'},
  {dicItemCode: '020060', dicItemName: '五级职员（正处）'},
  {dicItemCode: '020070', dicItemName: '六级职员（副处）'},
  {dicItemCode: '020080', dicItemName: '七级职员（正科）'},
  {dicItemCode: '020090', dicItemName: '八级职员（副科）'},
  {dicItemCode: '020100', dicItemName: '九级职员（科员）'},
  {dicItemCode: '020110', dicItemName: '十级职员（办事员）'},
  {dicItemCode: '020120', dicItemName: '未定级'},
  {dicItemCode: '030', dicItemName: '专业技术类职员雇员职务级别'},
  {dicItemCode: '030020', dicItemName: '正高级(教授级)'},
  {dicItemCode: '030030', dicItemName: '副高级(副教授级)'},
  {dicItemCode: '030040', dicItemName: '中级(讲师级)'},
  {dicItemCode: '030060', dicItemName: '助理级(助教级)'},
  {dicItemCode: '030070', dicItemName: '员级(教员级)'},
  {dicItemCode: '030080', dicItemName: '无职级'},
  {dicItemCode: '040', dicItemName: '公安警员职务层次'},
  {dicItemCode: '040010', dicItemName: '一级高级警长'},
  {dicItemCode: '040020', dicItemName: '二级高级警长'},
  {dicItemCode: '040030', dicItemName: '一级警长'},
  {dicItemCode: '040040', dicItemName: '二级警长'},
  {dicItemCode: '040050', dicItemName: '三级警长'},
  {dicItemCode: '040060', dicItemName: '四级警长'},
  {dicItemCode: '040070', dicItemName: '一级警员'},
  {dicItemCode: '040080', dicItemName: '二级警员'},
  {dicItemCode: '040090', dicItemName: '三级警员'},
  {dicItemCode: '040100', dicItemName: '四级警员'},
  {dicItemCode: '040110', dicItemName: '初级警员'},
  {dicItemCode: '040120', dicItemName: '见习警员'},
  {dicItemCode: '040130', dicItemName: '未定级'},
  {dicItemCode: '041', dicItemName: '公安技术警察职务层次'},
  {dicItemCode: '041010', dicItemName: '一级技术警察'},
  {dicItemCode: '041020', dicItemName: '二级技术警察'},
  {dicItemCode: '041030', dicItemName: '三级技术警察'},
  {dicItemCode: '041040', dicItemName: '四级技术警察'},
  {dicItemCode: '041050', dicItemName: '五级技术警察'},
  {dicItemCode: '041060', dicItemName: '六级技术警察'},
  {dicItemCode: '041070', dicItemName: '七级技术警察'},
  {dicItemCode: '041080', dicItemName: '八级技术警察'},
  {dicItemCode: '041090', dicItemName: '九级技术警察'},
  {dicItemCode: '041100', dicItemName: '十级技术警察'},
  {dicItemCode: '05', dicItemName: '军队职务级别'},
  {dicItemCode: '050', dicItemName: '军事，政治，后勤，装备军官职别'},
  {dicItemCode: '050010', dicItemName: '军委主席职'},
  {dicItemCode: '050020', dicItemName: '军委副主席职'},
  {dicItemCode: '050030', dicItemName: '军委秘书长'},
  {dicItemCode: '050040', dicItemName: '军委副秘书长'},
  {dicItemCode: '050050', dicItemName: '军委常委'},
  {dicItemCode: '050060', dicItemName: '军委委员职'},
  {dicItemCode: '050210', dicItemName: '正大军区职'},
  {dicItemCode: '050230', dicItemName: '副大军区职'},
  {dicItemCode: '050310', dicItemName: '正兵团级'},
  {dicItemCode: '050330', dicItemName: '副兵团级'},
  {dicItemCode: '050410', dicItemName: '正军职'},
  {dicItemCode: '050430', dicItemName: '副军职'},
  {dicItemCode: '050450', dicItemName: '准兵团级'},
  {dicItemCode: '050510', dicItemName: '正师职'},
  {dicItemCode: '050530', dicItemName: '副师职(正旅职)'},
  {dicItemCode: '050550', dicItemName: '准师级'},
  {dicItemCode: '050610', dicItemName: '正团职(副旅职)'},
  {dicItemCode: '050630', dicItemName: '副团职'},
  {dicItemCode: '050650', dicItemName: '准团级'},
  {dicItemCode: '050710', dicItemName: '正营职'},
  {dicItemCode: '050730', dicItemName: '副营职'},
  {dicItemCode: '050810', dicItemName: '正连职'},
  {dicItemCode: '050830', dicItemName: '副连职'},
  {dicItemCode: '050910', dicItemName: '正排职'},
  {dicItemCode: '060', dicItemName: '非专业技术文职干部职务级别'},
  {dicItemCode: '060110', dicItemName: '正部级'},
  {dicItemCode: '060120', dicItemName: '副部级'},
  {dicItemCode: '060210', dicItemName: '正局级'},
  {dicItemCode: '060220', dicItemName: '副局级'},
  {dicItemCode: '060310', dicItemName: '正处级'},
  {dicItemCode: '060320', dicItemName: '副处级'},
  {dicItemCode: '060410', dicItemName: '正科级'},
  {dicItemCode: '060420', dicItemName: '副科级'},
  {dicItemCode: '060510', dicItemName: '一级科员'},
  {dicItemCode: '060520', dicItemName: '二级科员'},
  {dicItemCode: '060600', dicItemName: '办事员'},
  {dicItemCode: '070', dicItemName: '专业技术军官，专业技术文职干部和专业技术文职人员技术等级'},
  {dicItemCode: '070010', dicItemName: '专业技术一级'},
  {dicItemCode: '070020', dicItemName: '专业技术二级'},
  {dicItemCode: '070030', dicItemName: '专业技术三级'},
  {dicItemCode: '070040', dicItemName: '专业技术四级'},
  {dicItemCode: '070050', dicItemName: '专业技术五级'},
  {dicItemCode: '070060', dicItemName: '专业技术六级'},
  {dicItemCode: '070070', dicItemName: '专业技术七级'},
  {dicItemCode: '070080', dicItemName: '专业技术八级'},
  {dicItemCode: '070090', dicItemName: '专业技术九级'},
  {dicItemCode: '070100', dicItemName: '专业技术十级'},
  {dicItemCode: '070110', dicItemName: '专业技术十一级'},
  {dicItemCode: '070120', dicItemName: '专业技术十二级'},
  {dicItemCode: '070130', dicItemName: '专业技术十三级'},
  {dicItemCode: '070140', dicItemName: '专业技术十四级'},
  {dicItemCode: '080', dicItemName: '非专业技术文职人员级别'},
  {dicItemCode: '080020', dicItemName: '二级职员'},
  {dicItemCode: '080030', dicItemName: '三级职员'},
  {dicItemCode: '080040', dicItemName: '四级职员'},
  {dicItemCode: '080050', dicItemName: '五级职员'},
  {dicItemCode: '080060', dicItemName: '六级职员'},
  {dicItemCode: '090', dicItemName: '士官职位级别'},
  {dicItemCode: '090010', dicItemName: '六级士官'},
  {dicItemCode: '090020', dicItemName: '五级士官'},
  {dicItemCode: '090030', dicItemName: '四级士官'},
  {dicItemCode: '090040', dicItemName: '三级士官'},
  {dicItemCode: '090050', dicItemName: '二级士官'},
  {dicItemCode: '090060', dicItemName: '一级士官'},
  {dicItemCode: '100', dicItemName: '技术工人岗位级别'},
  {dicItemCode: '100010', dicItemName: '高级技师'},
  {dicItemCode: '100020', dicItemName: '技师'},
  {dicItemCode: '100030', dicItemName: '高级技术工人'},
  {dicItemCode: '100040', dicItemName: '中级技术工人'},
  {dicItemCode: '100050', dicItemName: '初级技术工人'},
  {dicItemCode: '100060', dicItemName: '普通工人'},
  {dicItemCode: '110', dicItemName: '其他信息'},
  {dicItemCode: '110010', dicItemName: '未定级'},
  {dicItemCode: '120', dicItemName: '法官职务级别'},
  {dicItemCode: '120010', dicItemName: '一级高级法官'},
  {dicItemCode: '120020', dicItemName: '二级高级法官'},
  {dicItemCode: '120030', dicItemName: '三级高级法官'},
  {dicItemCode: '120040', dicItemName: '四级高级法官'},
  {dicItemCode: '120050', dicItemName: '一级法官'},
  {dicItemCode: '120060', dicItemName: '二级法官'},
  {dicItemCode: '120070', dicItemName: '三级法官'},
  {dicItemCode: '120080', dicItemName: '四级法官'},
  {dicItemCode: '120090', dicItemName: '五级法官'},
  {dicItemCode: '120100', dicItemName: '未定级'},
  {dicItemCode: '130', dicItemName: '检察官职务级别'},
  {dicItemCode: '130010', dicItemName: '一级高级检察官'},
  {dicItemCode: '130020', dicItemName: '二级高级检察官'},
  {dicItemCode: '130030', dicItemName: '三级高级检察官'},
  {dicItemCode: '130040', dicItemName: '四级高级检察官'},
  {dicItemCode: '130050', dicItemName: '一级检察官'},
  {dicItemCode: '130060', dicItemName: '二级检察官'},
  {dicItemCode: '130070', dicItemName: '三级检察官'},
  {dicItemCode: '130080', dicItemName: '四级检察官'},
  {dicItemCode: '130090', dicItemName: '五级检察官'},
  {dicItemCode: '130100', dicItemName: '未定级'},
];
